import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";


const comicNeue = Comic_Neue({
  subsets: ["latin"],
  preload: true,
  weight: ["400", "700"],
  variable: "--font-comic-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comicNeue.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
